In [1]:
import pandas as pd
import gc
from sklearn import preprocessing
import time
import math
import pickle
import numpy as np

In [2]:
total =  pickle.load(open('../../data/raw/total_high_level.pkl','rb+'))
total = total.reset_index(drop=True)

In [35]:
data = total.loc[(total["context_timestamp"] >= "20180907"),["user_id","user_id_shop_id","user_id_item_id","context_timestamp","is_trade"]]

In [36]:
data["apperance"] = 1

In [37]:
feature_name = "user_id"
data.sort_values(by=[feature_name, 'context_timestamp'], inplace=True)
data['apperance_nums_{}'.format(feature_name)]=data.groupby([feature_name])["apperance"].cumsum()  
df = data.groupby([feature_name])["apperance"].sum()  
result = pd.DataFrame({feature_name:df.index, 'apperance_nums_sum_{}'.format(feature_name):df.values})
data = data.reset_index().merge(result,on=feature_name, how="left").set_index("index")
data["apperance_nums_{}_ratio".format(feature_name)] = data['apperance_nums_{}'.format(feature_name)] / data['apperance_nums_sum_{}'.format(feature_name)]
del data['apperance_nums_{}'.format(feature_name)]
del data['apperance_nums_sum_{}'.format(feature_name)]

In [43]:
feature_name = "user_id_item_id"
data.sort_values(by=[feature_name, 'context_timestamp'], inplace=True)
data['apperance_nums_{}'.format(feature_name)]=data.groupby([feature_name])["apperance"].cumsum()  
df = data.groupby([feature_name])["apperance"].sum()  
result = pd.DataFrame({feature_name:df.index, 'apperance_nums_sum_{}'.format(feature_name):df.values})
data = data.reset_index().merge(result,on=feature_name, how="left").set_index("index")
data["apperance_nums_{}_ratio".format(feature_name)] = data['apperance_nums_{}'.format(feature_name)] / data['apperance_nums_sum_{}'.format(feature_name)]
del data['apperance_nums_{}'.format(feature_name)]
del data['apperance_nums_sum_{}'.format(feature_name)]

In [46]:
feature_name = "user_id_shop_id"
data.sort_values(by=[feature_name, 'context_timestamp'], inplace=True)
data['apperance_nums_{}'.format(feature_name)]=data.groupby([feature_name])["apperance"].cumsum()  
df = data.groupby([feature_name])["apperance"].sum()  
result = pd.DataFrame({feature_name:df.index, 'apperance_nums_sum_{}'.format(feature_name):df.values})
data = data.reset_index().merge(result,on=feature_name, how="left").set_index("index")
data["apperance_nums_{}_ratio".format(feature_name)] = data['apperance_nums_{}'.format(feature_name)] / data['apperance_nums_sum_{}'.format(feature_name)]
del data['apperance_nums_{}'.format(feature_name)]
del data['apperance_nums_sum_{}'.format(feature_name)]

,user_id,user_id_shop_id,user_id_item_id,context_timestamp,is_trade,apperance,apperance_nums_user_id_ratio,apperance_nums_user_id_shop_id_ratio,apperance_nums_user_id_item_id_ratio
index,,,,,,,,,
1499670,1000074566423999338,1000074566423999338-2278256423748352114,1000074566423999338-201985079106997115,2018-09-07 07:01:49,0.0,1,0.272727,0.500000,1.000000
10691580,1000156422323293142,1000156422323293142-8700217384942453188,1000156422323293142-4871666174523810401,2018-09-07 13:11:34,NaN,1,0.400000,0.500000,0.500000
10602577,1000156422323293142,1000156422323293142-1023589938552475312,1000156422323293142-7975472882283744927,2018-09-07 13:11:34,NaN,1,0.200000,0.500000,0.500000
1814434,1000161454719785683,1000161454719785683-8773069216086700622,1000161454719785683-4892754250998951986,2018-09-07 06:43:56,0.0,1,0.142857,0.500000,0.500000
5138648,1000223571756197468,1000223571756197468-6811605981917175813,1000223571756197468-3339484388578255984,2018-09-07 08:01:19,0.0,1,0.250000,0.500000,0.500000
12115824,10002556448406167,10002556448406167-5650096606432485293,10002556448406167-5910313785182165657,2018-09-07 23:51:31,NaN,1,0.750000,0.500000,0.500000
11496113,1000268485955124069,1000268485955124069-5649068782703001311,1000268485955124069-1618015350719705645,2018-09-07 15:17:29,NaN,1,0.500000,0.500000,0.500000
1587365,1000296628073709871,1000296628073709871-3454106708481091606,1000296628073709871-2108741172654263279,2018-09-07 00:53:28,0.0,1,0.500000,0.500000,1.000000
4810744,1000314307767484031,1000314307767484031-3811778554735800085,1000314307767484031-3988240765485434327,2018-09-07 11:36:06,0.0,1,0.666667,0.500000,0.500000
11154970,1000378511344966409,1000378511344966409-109199465876435687,1000378511344966409-7518974935522928936,2018-09-07 22:09:03,NaN,1,0.500000,0.500000,1.000000
5011137,100039474904675106,100039474904675106-8000379432761812975,100039474904675106-6155222815165396841,2018-09-07 07:21:18,0.0,1,0.800000,0.500000,1.000000
12001173,1000456648256920642,1000456648256920642-7585434829506891940,1000456648256920642-453341169162672679,2018-09-07 14:01:28,NaN,1,0.200000,0.500000,1.000000
1784304,1000588294369372084,1000588294369372084-6829438120144100,1000588294369372084-2024021676427114670,2018-09-07 00:09:12,0.0,1,0.200000,0.333333,0.333333
5138134,1000588294369372084,1000588294369372084-6829438120144100,1000588294369372084-2024021676427114670,2018-09-07 00:53:16,1.0,1,0.400000,0.666667,0.666667
11862557,1000651102233701878,1000651102233701878-740156843786285660,1000651102233701878-2985551727630696754,2018-09-07 22:15:23,NaN,1,0.166667,0.500000,0.500000
10545748,1000651102233701878,1000651102233701878-8528557226755339880,1000651102233701878-8564498640497337414,2018-09-07 22:16:41,NaN,1,0.333333,0.500000,1.000000
10505135,1000745990530529534,1000745990530529534-9212713621321316221,1000745990530529534-1747066204621159684,2018-09-07 16:40:50,NaN,1,0.600000,0.500000,1.000000
10741881,1000745990530529534,1000745990530529534-8415797958884845226,1000745990530529534-6082505667729648438,2018-09-07 16:39:10,NaN,1,0.200000,0.500000,1.000000
11611029,1000793587017844921,1000793587017844921-7542257787936945903,1000793587017844921-1956329417742695010,2018-09-07 17:30:11,NaN,1,0.250000,0.500000,1.000000
1764677,1000875062151403245,1000875062151403245-7505435321622204690,1000875062151403245-2910643720226148960,2018-09-07 00:27:16,0.0,1,0.111111,0.500000,0.500000
11667504,1000875062151403245,1000875062151403245-4378376126793363719,1000875062151403245-4427170860981006136,2018-09-07 13:10:16,NaN,1,0.666667,0.500000,0.500000
12091379,1000878918151142635,1000878918151142635-3237592927637940275,1000878918151142635-1112644051949136197,2018-09-07 18:25:23,NaN,1,0.500000,0.500000,0.500000
4733055,1000918687067743268,1000918687067743268-6374169938484010007,1000918687067743268-205817875056766354,2018-09-07 11:10:30,0.0,1,0.500000,0.500000,0.500000
11224112,1000923766879683938,1000923766879683938-1044142460517652410,1000923766879683938-4218252355048475711,2018-09-07 21:15:02,NaN,1,0.500000,0.500000,1.000000
11827139,100126492634674659,100126492634674659-8595315798269462858,100126492634674659-2959569049152828189,2018-09-07 22:20:22,NaN,1,0.400000,0.500000,1.000000
10457657,100126492634674659,100126492634674659-3910379687645822028,100126492634674659-8560044306445703311,2018-09-07 22:18:47,NaN,1,0.200000,0.500000,1.000000
4934670,1001281397394669800,1001281397394669800-490965553794122775,1001281397394669800-1534151417246086395,2018-09-07 11:39:52,0.0,1,0.250000,0.500000,0.500000
4993954,1001281397394669800,1001281397394669800-6811605981917175813,1001281397394669800-3339484388578255984,2018-09-07 11:39:52,0.0,1,0.500000,0.500000,0.500000
11212474,100136931781252674,100136931781252674-4842727546658135123,100136931781252674-2370151887112697574,2018-09-07 12:17:49,NaN,1,0.375000,0.500000,0.500000
11914232,100136931781252674,100136931781252674-6105333979086510808,100136931781252674-8540155435212391871,2018-09-07 12:16:50,NaN,1,0.125000,0.500000,0.500000
...,...,...,...,...,...,...,...,...,...
11902287,998548550226662256,998548550226662256-3377660265655473170,998548550226662256-7870397052629361115,2018-09-07 14:14:57,NaN,1,0.500000,0.500000,0.500000
11480627,998565323615124030,998565323615124030-1883764252276586999,998565323615124030-4309479078866864655,2018-09-07 13:33:50,NaN,1,0.500000,0.500000,0.500000
4997529,998567677539619354,998567677539619354-3822081225921131505,998567677539619354-7408741766847397938,2018-09-07 08:49:31,0.0,1,0.333333,0.500000,1.000000
10898782,998629573930988517,998629573930988517-776472467649581671,998629573930988517-2492147161872133776,2018-09-07 18:30:01,NaN,1,0.333333,0.500000,1.000000
11386879,998665370372984040,998665370372984040-6054561576443662826,998665370372984040-6578924898508670077,2018-09-07 22:25:42,NaN,1,0.333333,0.500000,0.500000
10952187,998781071155252491,998781071155252491-8580364919350657974,998781071155252491-2839586534301199906,2018-09-07 14:22:15,NaN,1,0.166667,0.500000,0.500000
5143143,99896296688033853,99896296688033853-5816448278833752997,99896296688033853-3811490533010405427,2018-09-07 11:33:01,0.0,1,0.666667,0.500000,1.000000
10778920,998997376077826366,998997376077826366-6059708240503014533,998997376077826366-349973663931486375,2018-09-07 12:44:01,NaN,1,0.368421,0.333333,0.333333
10732182,998997376077826366,998997376077826366-6059708240503014533,998997376077826366-349973663931486375,2018-09-07 23:40:10,NaN,1,0.894737,0.666667,0.666667
11769207,998997376077826366,998997376077826366-4484389675025288423,998997376077826366-9039933454227766565,2018-09-07 21:54:52,NaN,1,0.631579,0.500000,0.500000
11111103,99903849389316107,99903849389316107-5697602157715237079,99903849389316107-7342611462505803220,2018-09-07 23:14:39,NaN,1,0.333333,0.500000,1.000000
10929346,999041029364863239,999041029364863239-5861537598235078065,999041029364863239-3766071321138869883,2018-09-07 14:13:49,NaN,1,0.600000,0.500000,0.500000
4945926,99909276672825751,99909276672825751-7026204672789790103,99909276672825751-790888577066596046,2018-09-07 08:41:01,0.0,1,0.500000,0.500000,0.500000
4970951,999154925782429419,999154925782429419-6426386154833174284,999154925782429419-1563447177557162968,2018-09-07 00:20:55,0.0,1,0.111111,0.500000,0.500000
10763340,999197783008694054,999197783008694054-5028921791518370307,999197783008694054-8068330622312957856,2018-09-07 12:18:19,NaN,1,0.250000,0.500000,1.000000
4954282,999203726849392448,999203726849392448-6284348981498335889,999203726849392448-317577746633411748,2018-09-07 10:25:43,0.0,1,0.500000,0.500000,0.500000
11769206,999210272248641705,999210272248641705-1729413480166306872,999210272248641705-3912814527184887932,2018-09-07 20:21:55,NaN,1,0.500000,0.500000,0.500000
11728683,999215205659235150,999215205659235150-1171952833585796005,999215205659235150-6218051121546486143,2018-09-07 19:44:25,NaN,1,0.833333,0.500000,0.500000
11313879,999253832708094884,999253832708094884-5370127530129295365,999253832708094884-5440494232230116601,2018-09-07 20:14:26,NaN,1,0.666667,0.500000,0.500000
1574360,999257139005322286,999257139005322286-3313070011029594082,999257139005322286-2003486236470647027,2018-09-07 06:24:48,0.0,1,0.090909,0.500000,0.500000
10653327,999257139005322286,999257139005322286-419962842558897628,999257139005322286-4107222939064835421,2018-09-07 21:22:34,NaN,1,0.363636,0.500000,1.000000
11209968,999257139005322286,999257139005322286-419962842558897628,999257139005322286-7141123672865146037,2018-09-07 21:13:05,NaN,1,0.181818,0.250000,0.333333
10578204,999257139005322286,999257139005322286-419962842558897628,999257139005322286-7141123672865146037,2018-09-07 22:53:56,NaN,1,0.545455,0.750000,0.666667
10992445,999369615305506218,999369615305506218-3910379687645822028,999369615305506218-7854753044863311639,2018-09-07 14:50:06,NaN,1,0.400000,0.500000,1.000000
11074012,999526045732253449,999526045732253449-5516593978751753429,999526045732253449-4294995126623033794,2018-09-07 21:10:36,NaN,1,0.500000,0.500000,0.500000
1809063,999615380520041270,999615380520041270-9170255818621556433,999615380520041270-970000467077513197,2018-09-07 00:26:30,0.0,1,0.333333,0.500000,0.500000
10573982,999615671009913423,999615671009913423-5224729455054912431,999615671009913423-5620116155000937243,2018-09-07 12:24:29,NaN,1,0.500000,0.500000,0.500000
10543695,999617395670473132,999617395670473132-6539317034484425998,999617395670473132-8418839540413221438,2018-09-07 23:08:45,NaN,1,0.428571,0.500000,0.500000
11313412,99963324278574726,99963324278574726-4571232466434413955,99963324278574726-754616304956411728,2018-09-07 19:50:44,NaN,1,0.666667,0.500000,0.500000
1807014,999728974708808037,999728974708808037-3698823231212809200,999728974708808037-6335575970351173230,2018-09-07 10:13:38,0.0,1,0.666667,0.500000,1.000000

In [47]:
data = data.sort_index()

In [49]:
del data["user_id"]
del data["user_id_shop_id"]
del data["user_id_item_id"]
del data["context_timestamp"]
del data["apperance"]

In [51]:
data.to_pickle('../../data/processed/magric_feature.pkl')

In [53]:
data.head()

,is_trade,apperance_nums_user_id_ratio,apperance_nums_user_id_shop_id_ratio,apperance_nums_user_id_item_id_ratio
index,,,,
1488847,0.0,1.000000,1.0,1.0
1488848,0.0,1.000000,1.0,1.0
1488849,0.0,0.500000,0.5,1.0
1488850,0.0,0.800000,1.0,1.0
1488851,0.0,0.044444,1.0,1.0

In [55]:
data.loc[np.isnan(data["is_trade"])].describe()

,is_trade,apperance_nums_user_id_ratio,apperance_nums_user_id_shop_id_ratio,apperance_nums_user_id_item_id_ratio
count,0.0,1.729656e+06,1.729656e+06,1.729656e+06
mean,NaN,7.242957e-01,9.620222e-01,9.750271e-01
std,NaN,2.826090e-01,1.348847e-01,1.102462e-01
min,NaN,1.923077e-02,5.882353e-02,1.000000e-01
25%,NaN,5.000000e-01,1.000000e+00,1.000000e+00
50%,NaN,7.692308e-01,1.000000e+00,1.000000e+00
75%,NaN,1.000000e+00,1.000000e+00,1.000000e+00
max,NaN,1.000000e+00,1.000000e+00,1.000000e+00

In [61]:
data.loc[(~np.isnan(data["is_trade"])) & (data["apperance_nums_user_id_ratio"]<1)].shape

(681189, 4)